name: "debug_evals"
ckpt_dir: /scratch/ya255/lingua/final_runs/xmer_100k/checkpoints/0000100000
dump_dir: /scratch/ya255/lingua/evaldump
generator:
  max_tokens: 1024
  dtype: bf16
  temperature: 1.0
  top_p: 0.95
harness:
  tasks:
    - wikitext