# Template config, need to change dump_dir, data.root_dir and tokenizer.path

# dump_dir: !!CHANGETHIS!!
dump_dir: "/scratch/ya255/lingua/long_runs/mamba_long_v2"
name: "mambav2"

steps: 100_000
probe_freq: null
seed: 777



optim:
  lr: 3e-3
  weight_decay: 0.033
  warmup: 5000
  lr_min_ratio: 0.000001
  clip: 1.0

distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 512
  n_heads: 8
  n_groups: 2
  state_dim: 1024
  conv_size: 4
  n_layers: 8
  dt_bias: false

data:
    # root_dir: /scratch/ya255/lingua/setup/
    root_dir: /scratch/ya255/lingua/setup/data/
    sources:
        # fineweb_edu_10bt_shuffled: 100.0
        dclm_baseline_1.0_shuffled: 100.0
    batch_size: 80
    prefetch_size: 512
    seq_len: 1024
    n_views: 2
    load_async: true
    add_bos: true
    add_eos: true
    tokenizer:
        name: sp
        path: setup/l2tokenizer/tokenizer.model

profiling:
  run: true
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
    dump:
        every: 10000
        keep: 3
    eval:
        every: 5000
        keep: -1

logging:
    freq: 10
    wandb:
        project: "attamba_long"

eval:
    generator:
        max_tokens: 1024
        dtype: bf16
    harness:
        tasks:
            - wikitext

# async_eval_gpus: 8
# eval:
#   harness:
#     tasks:
#       - hellaswag
#       - nq_open
#       - piqa
#       - siqa
#       - csatqa
#       - winogrande
#       - arc
#       - race
#       - gsm8k
#       - bbh
#       - mmlu
#   generator:
#     compile_prefilling: false
#     reduce_generation_overhead: false
#     max_tokens: 16384
#     dtype: bf16

#   mp_size: 1
